# Generated by Django 4.2 on 2026-03-25 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Name (optional)')),
                ('question_text', models.TextField(verbose_name='Question')),
                ('answer', models.TextField(blank=True, verbose_name='Answer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
